kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgre-pv
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: vspheretkg
  resources:
    requests:
      storage: 15Gi
